
package test.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Sat Apr 13 11:20:13 CEST 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "add", namespace = "http://www.com.computer")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "add", namespace = "http://www.com.computer", propOrder = {"a", "b"})

public class Add {

    @XmlElement(name = "a")
    private int a;
    @XmlElement(name = "b")
    private int b;

    public int getA() {
        return this.a;
    }

    public void setA(int newA)  {
        this.a = newA;
    }

    public int getB() {
        return this.b;
    }

    public void setB(int newB)  {
        this.b = newB;
    }

}

