
package test.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.7
 * Sat Apr 13 11:32:10 CEST 2024
 * Generated source version: 3.5.7
 */

@XmlRootElement(name = "getCountryCodeByCityName", namespace = "http://www.com.computer")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCountryCodeByCityName", namespace = "http://www.com.computer")

public class GetCountryCodeByCityName {

    @XmlElement(name = "cityName")
    private java.lang.String cityName;

    public java.lang.String getCityName() {
        return this.cityName;
    }

    public void setCityName(java.lang.String newCityName)  {
        this.cityName = newCityName;
    }

}

